"""add progress tracking tables

Revision ID: a1b2c3d4e5f6
Revises: 6b20f44f6a00
Create Date: 2025-10-14 01:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '6b20f44f6a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add missing fields to chat_messages table
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('context', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
    
    # Create resource_progress table
    op.create_table('resource_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_index', sa.Integer(), nullable=False),
    sa.Column('resource_index', sa.Integer(), nullable=False),
    sa.Column('resource_url', sa.String(length=500), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_path_id'], ['user_learning_paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'learning_path_id', 'milestone_index', 'resource_index', 
                        name='_user_path_milestone_resource_uc')
    )
    
    # Create milestone_progress table
    op.create_table('milestone_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_path_id', sa.String(length=36), nullable=False),
    sa.Column('milestone_index', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learning_path_id'], ['user_learning_paths.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'learning_path_id', 'milestone_index', 
                        name='_user_path_milestone_uc')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestone_progress')
    op.drop_table('resource_progress')
    
    # Remove added fields from chat_messages table
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))
        batch_op.drop_column('context')
        batch_op.drop_column('conversation_id')
    # ### end Alembic commands ###
